// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3dRjjQ_bdl-MHgkAWE_fXnvTiOItzyhU',
    appId: '1:662821735608:web:01bd82b967bd929debb84d',
    messagingSenderId: '662821735608',
    projectId: 'katta-db-83fa7',
    authDomain: 'katta-db-83fa7.firebaseapp.com',
    storageBucket: 'katta-db-83fa7.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNnwScJqxCDsBUoCglr3eKqlaW071aNZw',
    appId: '1:662821735608:ios:15110f3496106dfbebb84d',
    messagingSenderId: '662821735608',
    projectId: 'katta-db-83fa7',
    storageBucket: 'katta-db-83fa7.firebasestorage.app',
    iosBundleId: 'com.example.kattaDb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3dRjjQ_bdl-MHgkAWE_fXnvTiOItzyhU',
    appId: '1:662821735608:web:5f16eb50456a8378ebb84d',
    messagingSenderId: '662821735608',
    projectId: 'katta-db-83fa7',
    authDomain: 'katta-db-83fa7.firebaseapp.com',
    storageBucket: 'katta-db-83fa7.firebasestorage.app',
  );
}
